export enum Hash {
    Bow,
    Boomerang,
    Hookshot,
    Bomb,
    Mushroom,
    Powder,
    IceRod,
    Pendant,
    Bombos,
    Ether,
    Quake,
    Lantern,
    Hammer,
    Shovel,
    Ocarina,
    BugNet,
    Book,
    Bottle,
    GreenPotion,
    Somaria,
    Cape,
    Mirror,
    Boots,
    Glove,
    Flippers,
    MoonPearl,
    Shield,
    Mail,
    Heart,
    Map,
    Compass,
    BigKey,
};

export enum Accessibility {
    Items = "items",
    Locations = "locations",
    Beatable = "none",
};

export enum Crystals {
    Zero = "0",
    One = "1",
    Two = "2",
    Three = "3",
    Four = "4",
    Five = "5",
    Six = "6",
    Seven = "7",
    Random = "random",
};

export enum Keysanity {
    Standard = "standard",
    Mc = "mc",
    Mcs = "mcs",
    Full = "full",
};

export enum BossShuffle {
    None = "none",
    Simple = "simple",
    Full = "full",
    Random = "random",
};

export enum EnemyDamage {
    Default = "default",
    Shuffled = "shuffled",
    Random = "random",
};

export enum EnemyHealth {
    Default = "default",
    Easy = "easy",
    Hard = "hard",
    Expert = "expert",
};

export enum EnemyShuffle {
    None = "none",
    Shuffled = "shuffled",
    Random = "random",
};

export enum Entrances {
    None = "none",
    Simple = "simple",
    Restricted = "restricted",
    Full = "full",
    Crossed = "crossed",
    Insanity = "insanity",
};

export enum Glitches {
    None = "none",
    Overworld = "overworld_glitches",
    Hybrid = "hybrid_major_glitches",
    Major = "major_glitches",
    NoLogic = "no_logic",
};

export enum Goals {
    DefeatGanon = "ganon",
    FastGanon = "fast_ganon",
    Pedestal = "pedestal",
    Dungeons = "dungeons",
    TriforceHunt = "triforce-hunt",
    Ganonhunt = "ganonhunt",
    Completionist = "completionist",
};

export enum Toggle {
    On = "on",
    Off = "off",
};

export enum ItemFunctionality {
    Normal = "normal",
    Hard = "hard",
    Expert = "expert",
};

export enum ItemPool {
    Normal = "normal",
    Hard = "hard",
    Expert = "expert",
    CrowdControl = "crowd_control",
};

export enum ItemPlacement {
    Basic = "basic",
    Advanced = "advanced",
};

export enum Language {
    English = "en",
    Francais = "fr",
    Deutsch = "de",
    Espanol = "es",
};

export enum WorldState {
    Open = "open",
    Standard = "standard",
    Inverted = "inverted",
    Retro = "retro",
};

export enum Weapons {
    Randomized = "randomized",
    Assured = "assured",
    Vanilla = "vanilla",
    Swordless = "swordless",
};

export enum Spoilers {
    On = "on",
    Off = "off",
    Generate = "generate",
    Mystery = "mystery",
};

export enum HeartSpeed {
    Normal = "normal",
    Half = "half",
    Quarter = "quarter",
    Double = "double",
    Off = "off",
};

export enum HeartColor {
    Red = "red",
    Yellow = "yellow",
    Green = "green",
    Blue = "blue",
};

export enum MenuSpeed {
    Normal = "normal",
    Slow = "slow",
    Fast = "fast",
    Instant = "instant",
};

export enum Items {
    Nothing = "Nothing",
    FighterSword = "L1Sword",
    FighterSwordShield = "L1SwordAndShield",
    MasterSword = "MasterSword",
    TemperedSword = "L3Sword",
    GoldSword = "L4Sword",
    BlueShield = "BlueShield",
    RedShield = "RedShield",
    MirrorShield = "MirrorShield",
    FireRod = "FireRod",
    IceRod = "IceRod",
    Hammer = "Hammer",
    Hookshot = "Hookshot",
    Bow = "Bow",
    Boomerang = "Boomerang",
    MagicPowder = "Powder",
    Bombos = "Bombos",
    Ether = "Ether",
    Quake = "Quake",
    Lamp = "Lamp",
    Shovel = "Shovel",
    Flute = "OcarinaInactive",
    FluteActive = "OcarinaActive",
    CaneOfSomaria = "CaneOfSomaria",
    BottleEmpty = "Bottle",
    HeartPiece = "PieceOfHeart",
    CaneOfByrna = "CaneOfByrna",
    Cape = "Cape",
    Mirror = "MagicMirror",
    PowerGlove = "PowerGlove",
    TitansMitt = "TitansMitt",
    BookOfMudora = "BookOfMudora",
    Flippers = "Flippers",
    MoonPearl = "MoonPearl",
    BugNet = "BugCatchingNet",
    BlueMail = "BlueMail",
    RedMail = "RedMail",
    OneBomb = "Bomb",
    ThreeBombs = "ThreeBombs",
    Mushroom = "Mushroom",
    RedBoomerang = "RedBoomerang",
    BottleRedPotion = "BottleWithRedPotion",
    BottleGreenPotion = "BottleWithGreenPotion",
    BottleBluePotion = "BottleWithBluePotion",
    TenBombs = "TenBombs",
    OneRupee = "OneRupee",
    FiveRupees = "FiveRupees",
    TwentyRupees = "TwentyRupees",
    GreenTwenty = "TwentyRupees2",
    BowAndArrows = "BowAndArrows",
    BowAndSilverArrows = "BowAndSilverArrows",
    BottleBee = "BottleWithBee",
    BottleGoldBee = "BottleWithGoldBee",
    BottleFairy = "BottleWithFairy",
    BottleRandom = "BottleWithRandom",
    HeartContainer = "BossHeartContainer",
    SancHeartContainer = "HeartContainer",
    OneHundredRupees = "OneHundredRupees",
    FiftyRupees = "FiftyRupees",
    Heart = "Heart",
    SingleArrow = "Arrow",
    TenArrows = "TenArrows",
    SmallMagic = "SmallMagic",
    ThreeHundredRupees = "ThreeHundredRupees",
    PegasusBoots = "PegasusBoots",
    BombUpgrade5 = "BombUpgrade5",
    BombUpgrade10 = "BombUpgrade10",
    ArrowUpgrade5 = "ArrowUpgrade5",
    ArrowUpgrade10 = "ArrowUpgrade10",
    HalfMagic = "HalfMagic",
    QuarterMagic = "QuarterMagic",
    SilverArrows = "SilverArrowUpgrade",
    Rupoor = "Rupoor",
    RedClock = "RedClock",
    BlueClock = "BlueClock",
    GreenClock = "GreenClock",
    ProgressiveSword = "ProgressiveSword",
    ProgressiveShield = "ProgressiveShield",
    ProgressiveArmor = "ProgressiveArmor",
    ProgressiveGlove = "ProgressiveGlove",
    ProgressiveBow = "ProgressiveBow",
    Triforce = "Triforce",
    TriforcePiece = "TriforcePiece",
    MapA1 = "MapA1",
    MapA2 = "MapA2",
    MapD1 = "MapD1",
    MapD2 = "MapD2",
    MapD3 = "MapD3",
    MapD4 = "MapD4",
    MapD5 = "MapD5",
    MapD6 = "MapD6",
    MapD7 = "MapD7",
    MapP1 = "MapP1",
    MapP2 = "MapP2",
    MapP3 = "MapP3",
    MapH1 = "MapH1",
    MapH2 = "MapH2",
    CompassA1 = "CompassA1",
    CompassA2 = "CompassA2",
    CompassD1 = "CompassD1",
    CompassD2 = "CompassD2",
    CompassD3 = "CompassD3",
    CompassD4 = "CompassD4",
    CompassD5 = "CompassD5",
    CompassD6 = "CompassD6",
    CompassD7 = "CompassD7",
    CompassP1 = "CompassP1",
    CompassP2 = "CompassP2",
    CompassP3 = "CompassP3",
    CompassH1 = "CompassH1",
    CompassH2 = "CompassH2",
    BigKeyA1 = "BigKeyA1",
    BigKeyA2 = "BigKeyA2",
    BigKeyD1 = "BigKeyD1",
    BigKeyD2 = "BigKeyD2",
    BigKeyD3 = "BigKeyD3",
    BigKeyD4 = "BigKeyD4",
    BigKeyD5 = "BigKeyD5",
    BigKeyD6 = "BigKeyD6",
    BigKeyD7 = "BigKeyD7",
    BigKeyP1 = "BigKeyP1",
    BigKeyP2 = "BigKeyP2",
    BigKeyP3 = "BigKeyP3",
    BigKeyH1 = "BigKeyH1",
    BigKeyH2 = "BigKeyH2",
    SmallKeyA1 = "KeyA1",
    SmallKeyA2 = "KeyA2",
    SmallKeyD1 = "KeyD1",
    SmallKeyD2 = "KeyD2",
    SmallKeyD3 = "KeyD3",
    SmallKeyD4 = "KeyD4",
    SmallKeyD5 = "KeyD5",
    SmallKeyD6 = "KeyD6",
    SmallKeyD7 = "KeyD7",
    SmallKeyP1 = "KeyP1",
    SmallKeyP2 = "KeyP2",
    SmallKeyP3 = "KeyP3",
    SmallKeyH1 = "KeyH1",
    SmallKeyH2 = "KeyH2",
};

export enum Prizes {
    GreenPendant = "PendantOfCourage",
    RedPendant = "PendantOfWisdom",
    BluePendant = "PendantOfPower",
    Crystal1 = "Crystal1",
    Crystal2 = "Crystal2",
    Crystal3 = "Crystal3",
    Crystal4 = "Crystal4",
    Crystal5 = "Crystal5",
    Crystal6 = "Crystal6",
    Crystal7 = "Crystal7",
};

export enum Medallions {
    Bombos = "Bombos",
    Ether = "Ether",
    Quake = "Quake",
};

export enum Bottles {
    BottleEmpty = "Bottle",
    BottleRedPotion = "BottleWithRedPotion",
    BottleGreenPotion = "BottleWithGreenPotion",
    BottleBluePotion = "BottleWithBluePotion",
    BottleBee = "BottleWithBee",
    BottleFairy = "BottleWithFairy",
    BottleGoldBee = "BottleWithGoldBee",
};

export enum Drops {
    Random = "auto_fill",
    BeeSwarm = "Bee",
    GoodBee = "BeeGood",
    Heart = "Heart",
    GreenRupee = "RupeeGreen",
    BlueRupee = "RupeeBlue",
    RedRupee = "RupeeRed",
    OneBomb = "BombRefill1",
    FourBombs = "BombRefill4",
    EightBombs = "BombRefill8",
    SmallMagic = "MagicRefillSmall",
    FullMagic = "MagicRefillFull",
    FiveArrows = "ArrowRefill5",
    TenArrows = "ArrowRefill10",
    Fairy = "Fairy",
};

export enum ItemLocations {
    SahaHutLeft = "U2FoYXNyYWhsYSdzIEh1dCAtIExlZnQ6MQ==",
    SahaHutMiddle = "U2FoYXNyYWhsYSdzIEh1dCAtIE1pZGRsZTox",
    SahaHutRight = "U2FoYXNyYWhsYSdzIEh1dCAtIFJpZ2h0OjE=",
    Sahasrahla = "U2FoYXNyYWhsYTox",
    KingZora = "S2luZyBab3JhOjE=",
    ZoraLedge = "Wm9yYSdzIExlZGdlOjE=",
    PotionShop = "UG90aW9uIFNob3A6MQ==",
    WaterfallFairyLeft = "V2F0ZXJmYWxsIEZhaXJ5IC0gTGVmdDox",
    WaterfallFairyRight = "V2F0ZXJmYWxsIEZhaXJ5IC0gUmlnaHQ6MQ==",
    Pedestal = "TWFzdGVyIFN3b3JkIFBlZGVzdGFsOjE=",
    KingsTomb = "S2luZydzIFRvbWI6MQ==",
    Tavern = "S2FrYXJpa28gVGF2ZXJuOjE=",
    ChickenHut = "Q2hpY2tlbiBIb3VzZTox",
    KakarikoWellTop = "S2FrYXJpa28gV2VsbCAtIFRvcDox",
    KakarikoWellLeft = "S2FrYXJpa28gV2VsbCAtIExlZnQ6MQ==",
    KakarikoWellMiddle = "S2FrYXJpa28gV2VsbCAtIE1pZGRsZTox",
    KakarikoWellRight = "S2FrYXJpa28gV2VsbCAtIFJpZ2h0OjE=",
    KakarikoWellBottom = "S2FrYXJpa28gV2VsbCAtIEJvdHRvbTox",
    BlindsHutTop = "QmxpbmQncyBIaWRlb3V0IC0gVG9wOjE=",
    BlindsHutLeft = "QmxpbmQncyBIaWRlb3V0IC0gTGVmdDox",
    BlindsHutRight = "QmxpbmQncyBIaWRlb3V0IC0gUmlnaHQ6MQ==",
    BlindsHutFarLeft = "QmxpbmQncyBIaWRlb3V0IC0gRmFyIExlZnQ6MQ==",
    BlindsHutFarRight = "QmxpbmQncyBIaWRlb3V0IC0gRmFyIFJpZ2h0OjE=",
    BonkRocks = "UGVnYXN1cyBSb2Nrczox",
    BottleVendor = "Qm90dGxlIE1lcmNoYW50OjE=",
    MagicBat = "TWFnaWMgQmF0OjE=",
    SickKid = "U2ljayBLaWQ6MQ==",
    LostWoodsHideout = "TG9zdCBXb29kcyBIaWRlb3V0OjE=",
    LumberjackTree = "THVtYmVyamFjayBUcmVlOjE=",
    GraveyardLedge = "R3JhdmV5YXJkIExlZGdlOjE=",
    MushroomSpot = "TXVzaHJvb206MQ==",
    DamChest = "Rmxvb2RnYXRlIENoZXN0OjE=",
    DamFloodedItem = "U3Vua2VuIFRyZWFzdXJlOjE=",
    LinksHouse = "TGluaydzIEhvdXNlOjE=",
    Aginah = "QWdpbmFoJ3MgQ2F2ZTox",
    MiniMoldormFarLeft = "TWluaSBNb2xkb3JtIENhdmUgLSBGYXIgTGVmdDox",
    MiniMoldormLeft = "TWluaSBNb2xkb3JtIENhdmUgLSBMZWZ0OjE=",
    MiniMoldormRight = "TWluaSBNb2xkb3JtIENhdmUgLSBSaWdodDox",
    MiniMoldormFarRight = "TWluaSBNb2xkb3JtIENhdmUgLSBGYXIgUmlnaHQ6MQ==",
    MiniMoldormNPC = "TWluaSBNb2xkb3JtIENhdmUgLSBOUEM6MQ==",
    IceRodCave = "SWNlIFJvZCBDYXZlOjE=",
    Hobo = "SG9ibzox",
    BombosTablet = "Qm9tYm9zIFRhYmxldDox",
    Cave45 = "Q2F2ZSA0NTox",
    CheckerboardCave = "Q2hlY2tlcmJvYXJkIENhdmU6MQ==",
    Library = "TGlicmFyeTox",
    RaceGame = "TWF6ZSBSYWNlOjE=",
    DesertLedge = "RGVzZXJ0IExlZGdlOjE=",
    HyliaIsland = "TGFrZSBIeWxpYSBJc2xhbmQ6MQ==",
    DigSpot = "Rmx1dGUgU3BvdDox",
    Sanctuary = "U2FuY3R1YXJ5OjE=",
    SewersBackLeft = "U2V3ZXJzIC0gU2VjcmV0IFJvb20gLSBMZWZ0OjE=",
    SewersBackMiddle = "U2V3ZXJzIC0gU2VjcmV0IFJvb20gLSBNaWRkbGU6MQ==",
    SewersBackRight = "U2V3ZXJzIC0gU2VjcmV0IFJvb20gLSBSaWdodDox",
    SewersDarkCross = "U2V3ZXJzIC0gRGFyayBDcm9zczox",
    EscapeBoomerangChest = "SHlydWxlIENhc3RsZSAtIEJvb21lcmFuZyBDaGVzdDox",
    EscapeMapChest = "SHlydWxlIENhc3RsZSAtIE1hcCBDaGVzdDox",
    EscapeZeldasCell = "SHlydWxlIENhc3RsZSAtIFplbGRhJ3MgQ2VsbDox",
    Uncle = "TGluaydzIFVuY2xlOjE=",
    UncleChest = "U2VjcmV0IFBhc3NhZ2U6MQ==",
    EasternCompassChest = "RWFzdGVybiBQYWxhY2UgLSBDb21wYXNzIENoZXN0OjE=",
    EasternBigChest = "RWFzdGVybiBQYWxhY2UgLSBCaWcgQ2hlc3Q6MQ==",
    EasternCannonballChest = "RWFzdGVybiBQYWxhY2UgLSBDYW5ub25iYWxsIENoZXN0OjE=",
    EasternBigKeyChest = "RWFzdGVybiBQYWxhY2UgLSBCaWcgS2V5IENoZXN0OjE=",
    EasternMapChest = "RWFzdGVybiBQYWxhY2UgLSBNYXAgQ2hlc3Q6MQ==",
    EasternBoss = "RWFzdGVybiBQYWxhY2UgLSBCb3NzOjE=",
    DesertBigChest = "RGVzZXJ0IFBhbGFjZSAtIEJpZyBDaGVzdDox",
    DesertMapChest = "RGVzZXJ0IFBhbGFjZSAtIE1hcCBDaGVzdDox",
    DesertTorch = "RGVzZXJ0IFBhbGFjZSAtIFRvcmNoOjE=",
    DesertBigKeyChest = "RGVzZXJ0IFBhbGFjZSAtIEJpZyBLZXkgQ2hlc3Q6MQ==",
    DesertCompassChest = "RGVzZXJ0IFBhbGFjZSAtIENvbXBhc3MgQ2hlc3Q6MQ==",
    DesertBoss = "RGVzZXJ0IFBhbGFjZSAtIEJvc3M6MQ==",
    OldMan = "T2xkIE1hbjox",
    SpecRockCave = "U3BlY3RhY2xlIFJvY2sgQ2F2ZTox",
    SpecRockTop = "U3BlY3RhY2xlIFJvY2s6MQ==",
    EtherTablet = "RXRoZXIgVGFibGV0OjE=",
    SpiralCave = "U3BpcmFsIENhdmU6MQ==",
    MimicCave = "TWltaWMgQ2F2ZTox",
    ParadoxLowFarLeft = "UGFyYWRveCBDYXZlIExvd2VyIC0gRmFyIExlZnQ6MQ==",
    ParadoxLowLeft = "UGFyYWRveCBDYXZlIExvd2VyIC0gTGVmdDox",
    ParadoxLowRight = "UGFyYWRveCBDYXZlIExvd2VyIC0gUmlnaHQ6MQ==",
    ParadoxLowDarRight = "UGFyYWRveCBDYXZlIExvd2VyIC0gRmFyIFJpZ2h0OjE=",
    ParadoxLowMiddle = "UGFyYWRveCBDYXZlIExvd2VyIC0gTWlkZGxlOjE=",
    ParadoxUpLeft = "UGFyYWRveCBDYXZlIFVwcGVyIC0gTGVmdDox",
    ParadoxUpRight = "UGFyYWRveCBDYXZlIFVwcGVyIC0gUmlnaHQ6MQ==",
    FloatingIsland = "RmxvYXRpbmcgSXNsYW5kOjE=",
    HeraBigKeyChest = "VG93ZXIgb2YgSGVyYSAtIEJpZyBLZXkgQ2hlc3Q6MQ==",
    HeraBasementCage = "VG93ZXIgb2YgSGVyYSAtIEJhc2VtZW50IENhZ2U6MQ==",
    HeraMapChest = "VG93ZXIgb2YgSGVyYSAtIE1hcCBDaGVzdDox",
    HeraCompassChest = "VG93ZXIgb2YgSGVyYSAtIENvbXBhc3MgQ2hlc3Q6MQ==",
    HeraBigChest = "VG93ZXIgb2YgSGVyYSAtIEJpZyBDaGVzdDox",
    HeraBoss = "VG93ZXIgb2YgSGVyYSAtIEJvc3M6MQ==",
    AgaFirstFloor = "Q2FzdGxlIFRvd2VyIC0gUm9vbSAwMzox",
    AgaDarkMaze = "Q2FzdGxlIFRvd2VyIC0gRGFyayBNYXplOjE=",
    SuperBunnyTop = "U3VwZXJidW5ueSBDYXZlIC0gVG9wOjE=",
    SuperBunnyBottom = "U3VwZXJidW5ueSBDYXZlIC0gQm90dG9tOjE=",
    HookshotTopRight = "SG9va3Nob3QgQ2F2ZSAtIFRvcCBSaWdodDox",
    HookshotTopLeft = "SG9va3Nob3QgQ2F2ZSAtIFRvcCBMZWZ0OjE=",
    HookshotBottomLeft = "SG9va3Nob3QgQ2F2ZSAtIEJvdHRvbSBMZWZ0OjE=",
    HookshotBottomRight = "SG9va3Nob3QgQ2F2ZSAtIEJvdHRvbSBSaWdodDox",
    SpikeCave = "U3Bpa2UgQ2F2ZTox",
    Catfish = "Q2F0ZmlzaDox",
    PyramidLedge = "UHlyYW1pZDox",
    PyramidFairyLeft = "UHlyYW1pZCBGYWlyeSAtIExlZnQ6MQ==",
    PyramidFairyRight = "UHlyYW1pZCBGYWlyeSAtIFJpZ2h0OjE=",
    Brewery = "QnJld2VyeTox",
    CShapedHouse = "Qy1TaGFwZWQgSG91c2U6MQ==",
    ChestGame = "Q2hlc3QgR2FtZTox",
    HammerPegs = "SGFtbWVyIFBlZ3M6MQ==",
    BumperCave = "QnVtcGVyIENhdmU6MQ==",
    Blacksmith = "QmxhY2tzbWl0aDox",
    PurpleChest = "UHVycGxlIENoZXN0OjE=",
    HypeCaveTop = "SHlwZSBDYXZlIC0gVG9wOjE=",
    HypeCaveMidRight = "SHlwZSBDYXZlIC0gTWlkZGxlIFJpZ2h0OjE=",
    HypeCaveMidLeft = "SHlwZSBDYXZlIC0gTWlkZGxlIExlZnQ6MQ==",
    HypeCaveBottom = "SHlwZSBDYXZlIC0gQm90dG9tOjE=",
    HypeCaveNPC = "SHlwZSBDYXZlIC0gTlBDOjE=",
    Stumpy = "U3R1bXB5OjE=",
    DigGame = "RGlnZ2luZyBHYW1lOjE=",
    MireShedLeft = "TWlyZSBTaGVkIC0gTGVmdDox",
    MireShedRight = "TWlyZSBTaGVkIC0gUmlnaHQ6MQ==",
    PodShooterRoom = "UGFsYWNlIG9mIERhcmtuZXNzIC0gU2hvb3RlciBSb29tOjE=",
    PodBigKeyChest = "UGFsYWNlIG9mIERhcmtuZXNzIC0gQmlnIEtleSBDaGVzdDox",
    PodArenaLedge = "UGFsYWNlIG9mIERhcmtuZXNzIC0gVGhlIEFyZW5hIC0gTGVkZ2U6MQ==",
    PodArenaBridge = "UGFsYWNlIG9mIERhcmtuZXNzIC0gVGhlIEFyZW5hIC0gQnJpZGdlOjE=",
    PodStalfosBasement = "UGFsYWNlIG9mIERhcmtuZXNzIC0gU3RhbGZvcyBCYXNlbWVudDox",
    PodMapChest = "UGFsYWNlIG9mIERhcmtuZXNzIC0gTWFwIENoZXN0OjE=",
    PodBigChest = "UGFsYWNlIG9mIERhcmtuZXNzIC0gQmlnIENoZXN0OjE=",
    PodCompassChest = "UGFsYWNlIG9mIERhcmtuZXNzIC0gQ29tcGFzcyBDaGVzdDox",
    PodHarmlessHellway = "UGFsYWNlIG9mIERhcmtuZXNzIC0gSGFybWxlc3MgSGVsbHdheTox",
    PodDarkBasementLeft = "UGFsYWNlIG9mIERhcmtuZXNzIC0gRGFyayBCYXNlbWVudCAtIExlZnQ6MQ==",
    PodDarkBasementRight = "UGFsYWNlIG9mIERhcmtuZXNzIC0gRGFyayBCYXNlbWVudCAtIFJpZ2h0OjE=",
    PodDarkMazeTop = "UGFsYWNlIG9mIERhcmtuZXNzIC0gRGFyayBNYXplIC0gVG9wOjE=",
    PodDarkMazeBottom = "UGFsYWNlIG9mIERhcmtuZXNzIC0gRGFyayBNYXplIC0gQm90dG9tOjE=",
    PodBoss = "UGFsYWNlIG9mIERhcmtuZXNzIC0gQm9zczox",
    SwampEntranceChest = "U3dhbXAgUGFsYWNlIC0gRW50cmFuY2U6MQ==",
    SwampBigChest = "U3dhbXAgUGFsYWNlIC0gQmlnIENoZXN0OjE=",
    SwampBigKeyChest = "U3dhbXAgUGFsYWNlIC0gQmlnIEtleSBDaGVzdDox",
    SwampMapChest = "U3dhbXAgUGFsYWNlIC0gTWFwIENoZXN0OjE=",
    SwampWestChest = "U3dhbXAgUGFsYWNlIC0gV2VzdCBDaGVzdDox",
    SwampCompassChest = "U3dhbXAgUGFsYWNlIC0gQ29tcGFzcyBDaGVzdDox",
    SwampFloodedLeft = "U3dhbXAgUGFsYWNlIC0gRmxvb2RlZCBSb29tIC0gTGVmdDox",
    SwampFloodedRight = "U3dhbXAgUGFsYWNlIC0gRmxvb2RlZCBSb29tIC0gUmlnaHQ6MQ==",
    SwampWaterfallRoom = "U3dhbXAgUGFsYWNlIC0gV2F0ZXJmYWxsIFJvb206MQ==",
    SwampBoss = "U3dhbXAgUGFsYWNlIC0gQm9zczox",
    SkullBigChest = "U2t1bGwgV29vZHMgLSBCaWcgQ2hlc3Q6MQ==",
    SkullBigKeyChest = "U2t1bGwgV29vZHMgLSBCaWcgS2V5IENoZXN0OjE=",
    SkullCompassChest = "U2t1bGwgV29vZHMgLSBDb21wYXNzIENoZXN0OjE=",
    SkullMapChest = "U2t1bGwgV29vZHMgLSBNYXAgQ2hlc3Q6MQ==",
    SkullBridgeChest = "U2t1bGwgV29vZHMgLSBCcmlkZ2UgUm9vbTox",
    SkullPotPrison = "U2t1bGwgV29vZHMgLSBQb3QgUHJpc29uOjE=",
    SkullPinballRoom = "U2t1bGwgV29vZHMgLSBQaW5iYWxsIFJvb206MQ==",
    SkullBoss = "U2t1bGwgV29vZHMgLSBCb3NzOjE=",
    ThievesAttic = "VGhpZXZlcycgVG93biAtIEF0dGljOjE=",
    ThievesBigKeyChest = "VGhpZXZlcycgVG93biAtIEJpZyBLZXkgQ2hlc3Q6MQ==",
    ThievesMapChest = "VGhpZXZlcycgVG93biAtIE1hcCBDaGVzdDox",
    ThievesCompassChest = "VGhpZXZlcycgVG93biAtIENvbXBhc3MgQ2hlc3Q6MQ==",
    ThievesAmbushChest = "VGhpZXZlcycgVG93biAtIEFtYnVzaCBDaGVzdDox",
    ThievesBigChest = "VGhpZXZlcycgVG93biAtIEJpZyBDaGVzdDox",
    ThievesBlindsCell = "VGhpZXZlcycgVG93biAtIEJsaW5kJ3MgQ2VsbDox",
    ThievesBoss = "VGhpZXZlcycgVG93biAtIEJvc3M6MQ==",
    IceBigKeyChest = "SWNlIFBhbGFjZSAtIEJpZyBLZXkgQ2hlc3Q6MQ==",
    IceCompassChest = "SWNlIFBhbGFjZSAtIENvbXBhc3MgQ2hlc3Q6MQ==",
    IceMapChest = "SWNlIFBhbGFjZSAtIE1hcCBDaGVzdDox",
    IceSpikeRoom = "SWNlIFBhbGFjZSAtIFNwaWtlIFJvb206MQ==",
    IceFreezorChest = "SWNlIFBhbGFjZSAtIEZyZWV6b3IgQ2hlc3Q6MQ==",
    IceTRoom = "SWNlIFBhbGFjZSAtIEljZWQgVCBSb29tOjE=",
    IceBigChest = "SWNlIFBhbGFjZSAtIEJpZyBDaGVzdDox",
    IceBoss = "SWNlIFBhbGFjZSAtIEJvc3M6MQ==",
    MireBigChest = "TWlzZXJ5IE1pcmUgLSBCaWcgQ2hlc3Q6MQ==",
    MireLobbyChest = "TWlzZXJ5IE1pcmUgLSBNYWluIExvYmJ5OjE=",
    MireBigKeyChest = "TWlzZXJ5IE1pcmUgLSBCaWcgS2V5IENoZXN0OjE=",
    MireCompassChest = "TWlzZXJ5IE1pcmUgLSBDb21wYXNzIENoZXN0OjE=",
    MireBridgeChest = "TWlzZXJ5IE1pcmUgLSBCcmlkZ2UgQ2hlc3Q6MQ==",
    MireMapChest = "TWlzZXJ5IE1pcmUgLSBNYXAgQ2hlc3Q6MQ==",
    MireSpikeChest = "TWlzZXJ5IE1pcmUgLSBTcGlrZSBDaGVzdDox",
    MireBoss = "TWlzZXJ5IE1pcmUgLSBCb3NzOjE=",
    TurtleChainChomps = "VHVydGxlIFJvY2sgLSBDaGFpbiBDaG9tcHM6MQ==",
    TurtleCompassChest = "VHVydGxlIFJvY2sgLSBDb21wYXNzIENoZXN0OjE=",
    TurtleRollerRoomLeft = "VHVydGxlIFJvY2sgLSBSb2xsZXIgUm9vbSAtIExlZnQ6MQ==",
    TurtleRollerRoomRight = "VHVydGxlIFJvY2sgLSBSb2xsZXIgUm9vbSAtIFJpZ2h0OjE=",
    TurtleBigChest = "VHVydGxlIFJvY2sgLSBCaWcgQ2hlc3Q6MQ==",
    TurtleBigKeyChest = "VHVydGxlIFJvY2sgLSBCaWcgS2V5IENoZXN0OjE=",
    TurtleCrystalrollerRoom = "VHVydGxlIFJvY2sgLSBDcnlzdGFyb2xsZXIgUm9vbTox",
    TurtleLaserBridgeLowerLeft = "VHVydGxlIFJvY2sgLSBFeWUgQnJpZGdlIC0gQm90dG9tIExlZnQ6MQ==",
    TurtleLaserBridgeLowerRight = "VHVydGxlIFJvY2sgLSBFeWUgQnJpZGdlIC0gQm90dG9tIFJpZ2h0OjE=",
    TurtleLaserBridgeTopLeft = "VHVydGxlIFJvY2sgLSBFeWUgQnJpZGdlIC0gVG9wIExlZnQ6MQ==",
    TurtleLaserBridgeTopRight = "VHVydGxlIFJvY2sgLSBFeWUgQnJpZGdlIC0gVG9wIFJpZ2h0OjE=",
    TurtleBoss = "VHVydGxlIFJvY2sgLSBCb3NzOjE=",
    GanonBobsTorch = "R2Fub24ncyBUb3dlciAtIEJvYidzIFRvcmNoOjE=",
    GanonStalfosRoomTopLeft = "R2Fub24ncyBUb3dlciAtIERNcyBSb29tIC0gVG9wIExlZnQ6MQ==",
    GanonStalfosRoomTopRight = "R2Fub24ncyBUb3dlciAtIERNcyBSb29tIC0gVG9wIFJpZ2h0OjE=",
    GanonStalfosRoomBottomLeft = "R2Fub24ncyBUb3dlciAtIERNcyBSb29tIC0gQm90dG9tIExlZnQ6MQ==",
    GanonStalfosRoomBottomRight = "R2Fub24ncyBUb3dlciAtIERNcyBSb29tIC0gQm90dG9tIFJpZ2h0OjE=",
    GanonRandoRoomTopLeft = "R2Fub24ncyBUb3dlciAtIFJhbmRvbWl6ZXIgUm9vbSAtIFRvcCBMZWZ0OjE=",
    GanonRandoRoomTopRight = "R2Fub24ncyBUb3dlciAtIFJhbmRvbWl6ZXIgUm9vbSAtIFRvcCBSaWdodDox",
    GanonRandoRoomBottomLeft = "R2Fub24ncyBUb3dlciAtIFJhbmRvbWl6ZXIgUm9vbSAtIEJvdHRvbSBMZWZ0OjE=",
    GanonRandoRoomBottomRight = "R2Fub24ncyBUb3dlciAtIFJhbmRvbWl6ZXIgUm9vbSAtIEJvdHRvbSBSaWdodDox",
    GanonFiresnakeRoom = "R2Fub24ncyBUb3dlciAtIEZpcmVzbmFrZSBSb29tOjE=",
    GanonMapChest = "R2Fub24ncyBUb3dlciAtIE1hcCBDaGVzdDox",
    GanonBigChest = "R2Fub24ncyBUb3dlciAtIEJpZyBDaGVzdDox",
    GanonHopeRoomLeft = "R2Fub24ncyBUb3dlciAtIEhvcGUgUm9vbSAtIExlZnQ6MQ==",
    GanonHopeRoomRight = "R2Fub24ncyBUb3dlciAtIEhvcGUgUm9vbSAtIFJpZ2h0OjE=",
    GanonBobsChest = "R2Fub24ncyBUb3dlciAtIEJvYidzIENoZXN0OjE=",
    GanonTileRoom = "R2Fub24ncyBUb3dlciAtIFRpbGUgUm9vbTox",
    GanonCompassRoomTopLeft = "R2Fub24ncyBUb3dlciAtIENvbXBhc3MgUm9vbSAtIFRvcCBMZWZ0OjE=",
    GanonCompassRoomTopRight = "R2Fub24ncyBUb3dlciAtIENvbXBhc3MgUm9vbSAtIFRvcCBSaWdodDox",
    GanonCompassRoomBottomLeft = "R2Fub24ncyBUb3dlciAtIENvbXBhc3MgUm9vbSAtIEJvdHRvbSBMZWZ0OjE=",
    GanonCompassRoomBottomRight = "R2Fub24ncyBUb3dlciAtIENvbXBhc3MgUm9vbSAtIEJvdHRvbSBSaWdodDox",
    GanonBigKeyChest = "R2Fub24ncyBUb3dlciAtIEJpZyBLZXkgQ2hlc3Q6MQ==",
    GanonBigKeyRoomLeft = "R2Fub24ncyBUb3dlciAtIEJpZyBLZXkgUm9vbSAtIExlZnQ6MQ==",
    GanonBigKeyRoomRight = "R2Fub24ncyBUb3dlciAtIEJpZyBLZXkgUm9vbSAtIFJpZ2h0OjE=",
    GanonHelmasaurRoomLeft = "R2Fub24ncyBUb3dlciAtIE1pbmkgSGVsbWFzYXVyIFJvb20gLSBMZWZ0OjE=",
    GanonHelmasaurRoomRight = "R2Fub24ncyBUb3dlciAtIE1pbmkgSGVsbWFzYXVyIFJvb20gLSBSaWdodDox",
    GanonPreMoldormChest = "R2Fub24ncyBUb3dlciAtIFByZS1Nb2xkb3JtIENoZXN0OjE=",
    GanonMoldormChest = "R2Fub24ncyBUb3dlciAtIE1vbGRvcm0gQ2hlc3Q6MQ==",
};

export enum PrizeLocations {
    EasternPalace = "RWFzdGVybiBQYWxhY2UgLSBQcml6ZTox",
    DesertPalace = "RGVzZXJ0IFBhbGFjZSAtIFByaXplOjE=",
    TowerOfHera = "VG93ZXIgb2YgSGVyYSAtIFByaXplOjE=",
    DarkPalace = "UGFsYWNlIG9mIERhcmtuZXNzIC0gUHJpemU6MQ==",
    SwampPalace = "U3dhbXAgUGFsYWNlIC0gUHJpemU6MQ==",
    SkullWoods = "U2t1bGwgV29vZHMgLSBQcml6ZTox",
    ThievesTown = "VGhpZXZlcycgVG93biAtIFByaXplOjE=",
    IcePalace = "SWNlIFBhbGFjZSAtIFByaXplOjE=",
    MiseryMire = "TWlzZXJ5IE1pcmUgLSBQcml6ZTox",
    TurtleRock = "VHVydGxlIFJvY2sgLSBQcml6ZTox",
};

export enum MedallionLocations {
    TurtleRock = "VHVydGxlIFJvY2sgTWVkYWxsaW9uOjE=",
    MiseryMire = "TWlzZXJ5IE1pcmUgTWVkYWxsaW9uOjE=",
};

export enum BottleLocations {
    WaterfallFairy = "V2F0ZXJmYWxsIEJvdHRsZTox",
    PyramidFairy = "UHlyYW1pZCBCb3R0bGU6MQ==",
};