export enum Hash {
    Bow,
    Boomerang,
    Hookshot,
    Bomb,
    Mushroom,
    Powder,
    IceRod,
    Pendant,
    Bombos,
    Ether,
    Quake,
    Lantern,
    Hammer,
    Shovel,
    Ocarina,
    BugNet,
    Book,
    Bottle,
    GreenPotion,
    Somaria,
    Cape,
    Mirror,
    Boots,
    Glove,
    Flippers,
    MoonPearl,
    Shield,
    Mail,
    Heart,
    Map,
    Compass,
    BigKey,
};

export enum Accessibility {
    Items = "items",
    Locations = "locations",
    Beatable = "none",
};

export enum Crystals {
    Zero = "0",
    One = "1",
    Two = "2",
    Three = "3",
    Four = "4",
    Five = "5",
    Six = "6",
    Seven = "7",
    Random = "random",
};

export enum Keysanity {
    Standard = "standard",
    Mc = "mc",
    Mcs = "mcs",
    Full = "full",
};

export enum BossShuffle {
    None = "none",
    Simple = "simple",
    Full = "full",
    Random = "random",
};

export enum EnemyDamage {
    Default = "default",
    Shuffled = "shuffled",
    Random = "random",
};

export enum EnemyHealth {
    Default = "default",
    Easy = "easy",
    Hard = "hard",
    Expert = "expert",
};

export enum EnemyShuffle {
    None = "none",
    Shuffled = "shuffled",
    Random = "random",
};

export enum Entrances {
    None = "none",
    Simple = "simple",
    Restricted = "restricted",
    Full = "full",
    Crossed = "crossed",
    Insanity = "insanity",
};

export enum Glitches {
    None = "none",
    Overworld = "overworld_glitches",
    Hybrid = "hybrid_major_glitches",
    Major = "major_glitches",
    NoLogic = "no_logic",
};

export enum Goals {
    DefeatGanon = "ganon",
    FastGanon = "fast_ganon",
    Pedestal = "pedestal",
    Dungeons = "dungeons",
    TriforceHunt = "triforce-hunt",
    Ganonhunt = "ganonhunt",
    Completionist = "completionist",
};

export enum Toggle {
    On = "on",
    Off = "off",
};

export enum ItemFunctionality {
    Normal = "normal",
    Hard = "hard",
    Expert = "expert",
};

export enum ItemPool {
    Normal = "normal",
    Hard = "hard",
    Expert = "expert",
    CrowdControl = "crowd_control",
};

export enum ItemPlacement {
    Basic = "basic",
    Advanced = "advanced",
};

export enum Language {
    English = "en",
    Francais = "fr",
    Deutsch = "de",
    Espanol = "es",
};

export enum WorldState {
    Open = "open",
    Standard = "standard",
    Inverted = "inverted",
    Retro = "retro",
};

export enum Weapons {
    Randomized = "randomized",
    Assured = "assured",
    Vanilla = "vanilla",
    Swordless = "swordless",
};

export enum Spoilers {
    On = "on",
    Off = "off",
    Generate = "generate",
    Mystery = "mystery",
};

export enum HeartSpeed {
    Normal = "normal",
    Half = "half",
    Quarter = "quarter",
    Double = "double",
    Off = "off",
};

export enum HeartColor {
    Red = "red",
    Yellow = "yellow",
    Green = "green",
    Blue = "blue",
};

export enum MenuSpeed {
    Normal = "normal",
    Slow = "slow",
    Fast = "fast",
    Instant = "instant",
};

export enum Items {
    Nothing = "Nothing",
    FighterSword = "L1Sword",
    FighterSwordShield = "L1SwordAndShield",
    MasterSword = "MasterSword",
    TemperedSword = "L3Sword",
    GoldSword = "L4Sword",
    BlueShield = "BlueShield",
    RedShield = "RedShield",
    MirrorShield = "MirrorShield",
    FireRod = "FireRod",
    IceRod = "IceRod",
    Hammer = "Hammer",
    Hookshot = "Hookshot",
    Bow = "Bow",
    Boomerang = "Boomerang",
    MagicPowder = "Powder",
    Bombos = "Bombos",
    Ether = "Ether",
    Quake = "Quake",
    Lamp = "Lamp",
    Shovel = "Shovel",
    Flute = "OcarinaInactive",
    FluteActive = "OcarinaActive",
    CaneOfSomaria = "CaneOfSomaria",
    BottleEmpty = "Bottle",
    HeartPiece = "PieceOfHeart",
    CaneOfByrna = "CaneOfByrna",
    Cape = "Cape",
    Mirror = "MagicMirror",
    PowerGlove = "PowerGlove",
    TitansMitt = "TitansMitt",
    BookOfMudora = "BookOfMudora",
    Flippers = "Flippers",
    MoonPearl = "MoonPearl",
    BugNet = "BugCatchingNet",
    BlueMail = "BlueMail",
    RedMail = "RedMail",
    OneBomb = "Bomb",
    ThreeBombs = "ThreeBombs",
    Mushroom = "Mushroom",
    RedBoomerang = "RedBoomerang",
    BottleRedPotion = "BottleWithRedPotion",
    BottleGreenPotion = "BottleWithGreenPotion",
    BottleBluePotion = "BottleWithBluePotion",
    TenBombs = "TenBombs",
    OneRupee = "OneRupee",
    FiveRupees = "FiveRupees",
    TwentyRupees = "TwentyRupees",
    GreenTwenty = "TwentyRupees2",
    BowAndArrows = "BowAndArrows",
    BowAndSilverArrows = "BowAndSilverArrows",
    BottleBee = "BottleWithBee",
    BottleGoldBee = "BottleWithGoldBee",
    BottleFairy = "BottleWithFairy",
    BottleRandom = "BottleWithRandom",
    HeartContainer = "BossHeartContainer",
    SancHeartContainer = "HeartContainer",
    OneHundredRupees = "OneHundredRupees",
    FiftyRupees = "FiftyRupees",
    Heart = "Heart",
    SingleArrow = "Arrow",
    TenArrows = "TenArrows",
    SmallMagic = "SmallMagic",
    ThreeHundredRupees = "ThreeHundredRupees",
    PegasusBoots = "PegasusBoots",
    BombUpgrade5 = "BombUpgrade5",
    BombUpgrade10 = "BombUpgrade10",
    ArrowUpgrade5 = "ArrowUpgrade5",
    ArrowUpgrade10 = "ArrowUpgrade10",
    HalfMagic = "HalfMagic",
    QuarterMagic = "QuarterMagic",
    SilverArrows = "SilverArrowUpgrade",
    Rupoor = "Rupoor",
    RedClock = "RedClock",
    BlueClock = "BlueClock",
    GreenClock = "GreenClock",
    ProgressiveSword = "ProgressiveSword",
    ProgressiveShield = "ProgressiveShield",
    ProgressiveArmor = "ProgressiveArmor",
    ProgressiveGlove = "ProgressiveGlove",
    ProgressiveBow = "ProgressiveBow",
    Triforce = "Triforce",
    TriforcePiece = "TriforcePiece",
    MapA1 = "MapA1",
    MapA2 = "MapA2",
    MapD1 = "MapD1",
    MapD2 = "MapD2",
    MapD3 = "MapD3",
    MapD4 = "MapD4",
    MapD5 = "MapD5",
    MapD6 = "MapD6",
    MapD7 = "MapD7",
    MapP1 = "MapP1",
    MapP2 = "MapP2",
    MapP3 = "MapP3",
    MapH1 = "MapH1",
    MapH2 = "MapH2",
    CompassA1 = "CompassA1",
    CompassA2 = "CompassA2",
    CompassD1 = "CompassD1",
    CompassD2 = "CompassD2",
    CompassD3 = "CompassD3",
    CompassD4 = "CompassD4",
    CompassD5 = "CompassD5",
    CompassD6 = "CompassD6",
    CompassD7 = "CompassD7",
    CompassP1 = "CompassP1",
    CompassP2 = "CompassP2",
    CompassP3 = "CompassP3",
    CompassH1 = "CompassH1",
    CompassH2 = "CompassH2",
    BigKeyA1 = "BigKeyA1",
    BigKeyA2 = "BigKeyA2",
    BigKeyD1 = "BigKeyD1",
    BigKeyD2 = "BigKeyD2",
    BigKeyD3 = "BigKeyD3",
    BigKeyD4 = "BigKeyD4",
    BigKeyD5 = "BigKeyD5",
    BigKeyD6 = "BigKeyD6",
    BigKeyD7 = "BigKeyD7",
    BigKeyP1 = "BigKeyP1",
    BigKeyP2 = "BigKeyP2",
    BigKeyP3 = "BigKeyP3",
    BigKeyH1 = "BigKeyH1",
    BigKeyH2 = "BigKeyH2",
    SmallKeyA1 = "KeyA1",
    SmallKeyA2 = "KeyA2",
    SmallKeyD1 = "KeyD1",
    SmallKeyD2 = "KeyD2",
    SmallKeyD3 = "KeyD3",
    SmallKeyD4 = "KeyD4",
    SmallKeyD5 = "KeyD5",
    SmallKeyD6 = "KeyD6",
    SmallKeyD7 = "KeyD7",
    SmallKeyP1 = "KeyP1",
    SmallKeyP2 = "KeyP2",
    SmallKeyP3 = "KeyP3",
    SmallKeyH1 = "KeyH1",
    SmallKeyH2 = "KeyH2",
};

export enum Prizes {
    GreenPendant = "PendantOfCourage",
    RedPendant = "PendantOfWisdom",
    BluePendant = "PendantOfPower",
    Crystal1 = "Crystal1",
    Crystal2 = "Crystal2",
    Crystal3 = "Crystal3",
    Crystal4 = "Crystal4",
    Crystal5 = "Crystal5",
    Crystal6 = "Crystal6",
    Crystal7 = "Crystal7",
};

export enum Medallions {
    Bombos = "Bombos",
    Ether = "Ether",
    Quake = "Quake",
};

export enum Bottles {
    BottleEmpty = "Bottle",
    BottleRedPotion = "BottleWithRedPotion",
    BottleGreenPotion = "BottleWithGreenPotion",
    BottleBluePotion = "BottleWithBluePotion",
    BottleBee = "BottleWithBee",
    BottleFairy = "BottleWithFairy",
    BottleGoldBee = "BottleWithGoldBee",
};

export enum Drops {
    Random = "auto_fill",
    BeeSwarm = "Bee",
    GoodBee = "BeeGood",
    Heart = "Heart",
    GreenRupee = "RupeeGreen",
    BlueRupee = "RupeeBlue",
    RedRupee = "RupeeRed",
    OneBomb = "BombRefill1",
    FourBombs = "BombRefill4",
    EightBombs = "BombRefill8",
    SmallMagic = "MagicRefillSmall",
    FullMagic = "MagicRefillFull",
    FiveArrows = "ArrowRefill5",
    TenArrows = "ArrowRefill10",
    Fairy = "Fairy",
};

export enum ItemLocations {
    SahaHutLeft = "U2FoYXNyYWhsYSdzIEh1dCAtIExlZnQ6MQ==",
    SahaHutMiddle = "U2FoYXNyYWhsYSdzIEh1dCAtIE1pZGRsZTox",
    SahaHutRight = "U2FoYXNyYWhsYSdzIEh1dCAtIFJpZ2h0OjE=",
    Sahasrahla = "U2FoYXNyYWhsYTox",
    KingZora = "S2luZyBab3JhOjE=",
    ZoraLedge = "Wm9yYSdzIExlZGdlOjE=",
    PotionShop = "UG90aW9uIFNob3A6MQ==",
    WaterfallFairyLeft = "V2F0ZXJmYWxsIEZhaXJ5IC0gTGVmdDox",
    WaterfallFairyRight = "V2F0ZXJmYWxsIEZhaXJ5IC0gUmlnaHQ6MQ==",
    Pedestal = "TWFzdGVyIFN3b3JkIFBlZGVzdGFsOjE=",
    KingsTomb = "S2luZydzIFRvbWI6MQ==",
    Tavern = "S2FrYXJpa28gVGF2ZXJuOjE=",
    ChickenHut = "Q2hpY2tlbiBIb3VzZTox",
    KakarikoWellTop = "S2FrYXJpa28gV2VsbCAtIFRvcDox",
    KakarikoWellLeft = "S2FrYXJpa28gV2VsbCAtIExlZnQ6MQ==",
    KakarikoWellMiddle = "S2FrYXJpa28gV2VsbCAtIE1pZGRsZTox",
    KakarikoWellRight = "S2FrYXJpa28gV2VsbCAtIFJpZ2h0OjE=",
    KakarikoWellBottom = "S2FrYXJpa28gV2VsbCAtIEJvdHRvbTox",
    BlindsHutTop = "QmxpbmQncyBIaWRlb3V0IC0gVG9wOjE=",
    BlindsHutLeft = "QmxpbmQncyBIaWRlb3V0IC0gTGVmdDox",
    BlindsHutRight = "QmxpbmQncyBIaWRlb3V0IC0gUmlnaHQ6MQ==",
    BlindsHutFarLeft = "QmxpbmQncyBIaWRlb3V0IC0gRmFyIExlZnQ6MQ==",
    BlindsHutFarRight = "QmxpbmQncyBIaWRlb3V0IC0gRmFyIFJpZ2h0OjE=",
    BonkRocks = "UGVnYXN1cyBSb2Nrczox",
    BottleVendor = "Qm90dGxlIE1lcmNoYW50OjE=",
    MagicBat = "TWFnaWMgQmF0OjE=",
    SickKid = "U2ljayBLaWQ6MQ==",
    LostWoodsHideout = "TG9zdCBXb29kcyBIaWRlb3V0OjE=",
    LumberjackTree = "THVtYmVyamFjayBUcmVlOjE=",
    GraveyardLedge = "R3JhdmV5YXJkIExlZGdlOjE=",
    MushroomSpot = "TXVzaHJvb206MQ==",
    DamChest = "Rmxvb2RnYXRlIENoZXN0OjE=",
    DamFloodedItem = "U3Vua2VuIFRyZWFzdXJlOjE=",
    LinksHouse = "TGluaydzIEhvdXNlOjE=",
    Aginah = "QWdpbmFoJ3MgQ2F2ZTox",
    MiniMoldormFarLeft = "TWluaSBNb2xkb3JtIENhdmUgLSBGYXIgTGVmdDox",
    MiniMoldormLeft = "TWluaSBNb2xkb3JtIENhdmUgLSBMZWZ0OjE=",
    MiniMoldormRight = "TWluaSBNb2xkb3JtIENhdmUgLSBSaWdodDox",
    MiniMoldormFarRight = "TWluaSBNb2xkb3JtIENhdmUgLSBGYXIgUmlnaHQ6MQ==",
    MiniMoldormNPC = "TWluaSBNb2xkb3JtIENhdmUgLSBOUEM6MQ==",
    IceRodCave = "SWNlIFJvZCBDYXZlOjE=",
    Hobo = "SG9ibzox",
    BombosTablet = "Qm9tYm9zIFRhYmxldDox",
    Cave45 = "Q2F2ZSA0NTox",
    CheckerboardCave = "Q2hlY2tlcmJvYXJkIENhdmU6MQ==",
    Library = "TGlicmFyeTox",
    RaceGame = "TWF6ZSBSYWNlOjE=",
    DesertLedge = "RGVzZXJ0IExlZGdlOjE=",
    HyliaIsland = "TGFrZSBIeWxpYSBJc2xhbmQ6MQ==",
    DigSpot = "Rmx1dGUgU3BvdDox",
    Sanctuary = "U2FuY3R1YXJ5OjE=",
    SewersBackLeft = "U2V3ZXJzIC0gU2VjcmV0IFJvb20gLSBMZWZ0OjE=",
    SewersBackMiddle = "U2V3ZXJzIC0gU2VjcmV0IFJvb20gLSBNaWRkbGU6MQ==",
    SewersBackRight = "U2V3ZXJzIC0gU2VjcmV0IFJvb20gLSBSaWdodDox",
    SewersDarkCross = "U2V3ZXJzIC0gRGFyayBDcm9zczox",
    EscapeBoomerangChest = "SHlydWxlIENhc3RsZSAtIEJvb21lcmFuZyBDaGVzdDox",
    EscapeMapChest = "SHlydWxlIENhc3RsZSAtIE1hcCBDaGVzdDox",
    EscapeZeldasCell = "SHlydWxlIENhc3RsZSAtIFplbGRhJ3MgQ2VsbDox",
    Uncle = "TGluaydzIFVuY2xlOjE=",
    UncleChest = "U2VjcmV0IFBhc3NhZ2U6MQ==",
    EasternCompassChest = "RWFzdGVybiBQYWxhY2UgLSBDb21wYXNzIENoZXN0OjE=",
    EasternBigChest = "RWFzdGVybiBQYWxhY2UgLSBCaWcgQ2hlc3Q6MQ==",
    EasternCannonballChest = "RWFzdGVybiBQYWxhY2UgLSBDYW5ub25iYWxsIENoZXN0OjE=",
    EasternBigKeyChest = "RWFzdGVybiBQYWxhY2UgLSBCaWcgS2V5IENoZXN0OjE=",
    EasternMapChest = "RWFzdGVybiBQYWxhY2UgLSBNYXAgQ2hlc3Q6MQ==",
    EasternBoss = "RWFzdGVybiBQYWxhY2UgLSBCb3NzOjE=",
    DesertBigChest = "RGVzZXJ0IFBhbGFjZSAtIEJpZyBDaGVzdDox",
    DesertMapChest = "RGVzZXJ0IFBhbGFjZSAtIE1hcCBDaGVzdDox",
    DesertTorch = "RGVzZXJ0IFBhbGFjZSAtIFRvcmNoOjE=",
    DesertBigKeyChest = "RGVzZXJ0IFBhbGFjZSAtIEJpZyBLZXkgQ2hlc3Q6MQ==",
    DesertCompassChest = "RGVzZXJ0IFBhbGFjZSAtIENvbXBhc3MgQ2hlc3Q6MQ==",
    DesertBoss = "RGVzZXJ0IFBhbGFjZSAtIEJvc3M6MQ==",
    OldMan = "T2xkIE1hbjox",
    SpecRockCave = "U3BlY3RhY2xlIFJvY2sgQ2F2ZTox",
    SpecRockTop = "U3BlY3RhY2xlIFJvY2s6MQ==",
    EtherTablet = "RXRoZXIgVGFibGV0OjE=",
    SpiralCave = "U3BpcmFsIENhdmU6MQ==",
    MimicCave = "TWltaWMgQ2F2ZTox",
    ParadoxLowFarLeft = "UGFyYWRveCBDYXZlIExvd2VyIC0gRmFyIExlZnQ6MQ==",
    ParadoxLowLeft = "UGFyYWRveCBDYXZlIExvd2VyIC0gTGVmdDox",
    ParadoxLowRight = "UGFyYWRveCBDYXZlIExvd2VyIC0gUmlnaHQ6MQ==",
    ParadoxLowDarRight = "UGFyYWRveCBDYXZlIExvd2VyIC0gRmFyIFJpZ2h0OjE=",
    ParadoxLowMiddle = "UGFyYWRveCBDYXZlIExvd2VyIC0gTWlkZGxlOjE=",
    ParadoxUpLeft = "UGFyYWRveCBDYXZlIFVwcGVyIC0gTGVmdDox",
    ParadoxUpRight = "UGFyYWRveCBDYXZlIFVwcGVyIC0gUmlnaHQ6MQ==",
    FloatingIsland = "RmxvYXRpbmcgSXNsYW5kOjE=",
    HeraBigKeyChest = "VG93ZXIgb2YgSGVyYSAtIEJpZyBLZXkgQ2hlc3Q6MQ==",
    HeraBasementCage = "VG93ZXIgb2YgSGVyYSAtIEJhc2VtZW50IENhZ2U6MQ==",
    HeraMapChest = "VG93ZXIgb2YgSGVyYSAtIE1hcCBDaGVzdDox",
    HeraCompassChest = "VG93ZXIgb2YgSGVyYSAtIENvbXBhc3MgQ2hlc3Q6MQ==",
    HeraBigChest = "VG93ZXIgb2YgSGVyYSAtIEJpZyBDaGVzdDox",
    HeraBoss = "VG93ZXIgb2YgSGVyYSAtIEJvc3M6MQ==",
    AgaFirstFloor = "Q2FzdGxlIFRvd2VyIC0gUm9vbSAwMzox",
    AgaDarkMaze = "Q2FzdGxlIFRvd2VyIC0gRGFyayBNYXplOjE=",
    SuperBunnyTop = "U3VwZXJidW5ueSBDYXZlIC0gVG9wOjE=",
    SuperBunnyBottom = "U3VwZXJidW5ueSBDYXZlIC0gQm90dG9tOjE=",
    HookshotTopRight = "SG9va3Nob3QgQ2F2ZSAtIFRvcCBSaWdodDox",
    HookshotTopLeft = "SG9va3Nob3QgQ2F2ZSAtIFRvcCBMZWZ0OjE=",
    HookshotBottomLeft = "SG9va3Nob3QgQ2F2ZSAtIEJvdHRvbSBMZWZ0OjE=",
    HookshotBottomRight = "SG9va3Nob3QgQ2F2ZSAtIEJvdHRvbSBSaWdodDox",
    SpikeCave = "U3Bpa2UgQ2F2ZTox",
    Catfish = "Q2F0ZmlzaDox",
    PyramidLedge = "UHlyYW1pZDox",
    PyramidFairyLeft = "UHlyYW1pZCBGYWlyeSAtIExlZnQ6MQ==",
    PyramidFairyRight = "UHlyYW1pZCBGYWlyeSAtIFJpZ2h0OjE=",
    Brewery = "QnJld2VyeTox",
    CShapedHouse = "Qy1TaGFwZWQgSG91c2U6MQ==",
    ChestGame = "Q2hlc3QgR2FtZTox",
    HammerPegs = "SGFtbWVyIFBlZ3M6MQ==",
    BumperCave = "QnVtcGVyIENhdmU6MQ==",
    Blacksmith = "QmxhY2tzbWl0aDox",
    PurpleChest = "UHVycGxlIENoZXN0OjE=",
    HypeCaveTop = "SHlwZSBDYXZlIC0gVG9wOjE=",
    HypeCaveMidRight = "SHlwZSBDYXZlIC0gTWlkZGxlIFJpZ2h0OjE=",
    HypeCaveMidLeft = "SHlwZSBDYXZlIC0gTWlkZGxlIExlZnQ6MQ==",
    HypeCaveBottom = "SHlwZSBDYXZlIC0gQm90dG9tOjE=",
    HypeCaveNPC = "SHlwZSBDYXZlIC0gTlBDOjE=",
    Stumpy = "U3R1bXB5OjE=",
    DigGame = "RGlnZ2luZyBHYW1lOjE=",
    MireShedLeft = "TWlyZSBTaGVkIC0gTGVmdDox",
    MireShedRight = "TWlyZSBTaGVkIC0gUmlnaHQ6MQ==",
    PodShooterRoom = "UGFsYWNlIG9mIERhcmtuZXNzIC0gU2hvb3RlciBSb29tOjE=",
    PodBigKeyChest = "UGFsYWNlIG9mIERhcmtuZXNzIC0gQmlnIEtleSBDaGVzdDox",
    PodArenaLedge = "UGFsYWNlIG9mIERhcmtuZXNzIC0gVGhlIEFyZW5hIC0gTGVkZ2U6MQ==",
    PodArenaBridge = "UGFsYWNlIG9mIERhcmtuZXNzIC0gVGhlIEFyZW5hIC0gQnJpZGdlOjE=",
    PodStalfosBasement = "UGFsYWNlIG9mIERhcmtuZXNzIC0gU3RhbGZvcyBCYXNlbWVudDox",
    PodMapChest = "UGFsYWNlIG9mIERhcmtuZXNzIC0gTWFwIENoZXN0OjE=",
    PodBigChest = "UGFsYWNlIG9mIERhcmtuZXNzIC0gQmlnIENoZXN0OjE=",
    PodCompassChest = "UGFsYWNlIG9mIERhcmtuZXNzIC0gQ29tcGFzcyBDaGVzdDox",
    PodHarmlessHellway = "UGFsYWNlIG9mIERhcmtuZXNzIC0gSGFybWxlc3MgSGVsbHdheTox",
    PodDarkBasementLeft = "UGFsYWNlIG9mIERhcmtuZXNzIC0gRGFyayBCYXNlbWVudCAtIExlZnQ6MQ==",
    PodDarkBasementRight = "UGFsYWNlIG9mIERhcmtuZXNzIC0gRGFyayBCYXNlbWVudCAtIFJpZ2h0OjE=",
    PodDarkMazeTop = "UGFsYWNlIG9mIERhcmtuZXNzIC0gRGFyayBNYXplIC0gVG9wOjE=",
    PodDarkMazeBottom = "UGFsYWNlIG9mIERhcmtuZXNzIC0gRGFyayBNYXplIC0gQm90dG9tOjE=",
    PodBoss = "UGFsYWNlIG9mIERhcmtuZXNzIC0gQm9zczox",
    SwampEntranceChest = "U3dhbXAgUGFsYWNlIC0gRW50cmFuY2U6MQ==",
    SwampBigChest = "U3dhbXAgUGFsYWNlIC0gQmlnIENoZXN0OjE=",
    SwampBigKeyChest = "U3dhbXAgUGFsYWNlIC0gQmlnIEtleSBDaGVzdDox",
    SwampMapChest = "U3dhbXAgUGFsYWNlIC0gTWFwIENoZXN0OjE=",
    SwampWestChest = "U3dhbXAgUGFsYWNlIC0gV2VzdCBDaGVzdDox",
    SwampCompassChest = "U3dhbXAgUGFsYWNlIC0gQ29tcGFzcyBDaGVzdDox",
    SwampFloodedLeft = "U3dhbXAgUGFsYWNlIC0gRmxvb2RlZCBSb29tIC0gTGVmdDox",
    SwampFloodedRight = "U3dhbXAgUGFsYWNlIC0gRmxvb2RlZCBSb29tIC0gUmlnaHQ6MQ==",
    SwampWaterfallRoom = "U3dhbXAgUGFsYWNlIC0gV2F0ZXJmYWxsIFJvb206MQ==",
    SwampBoss = "U3dhbXAgUGFsYWNlIC0gQm9zczox",
    SkullBigChest = "U2t1bGwgV29vZHMgLSBCaWcgQ2hlc3Q6MQ==",
    SkullBigKeyChest = "U2t1bGwgV29vZHMgLSBCaWcgS2V5IENoZXN0OjE=",
    SkullCompassChest = "U2t1bGwgV29vZHMgLSBDb21wYXNzIENoZXN0OjE=",
    SkullMapChest = "U2t1bGwgV29vZHMgLSBNYXAgQ2hlc3Q6MQ==",
    SkullBridgeChest = "U2t1bGwgV29vZHMgLSBCcmlkZ2UgUm9vbTox",
    SkullPotPrison = "U2t1bGwgV29vZHMgLSBQb3QgUHJpc29uOjE=",
    SkullPinballRoom = "U2t1bGwgV29vZHMgLSBQaW5iYWxsIFJvb206MQ==",
    SkullBoss = "U2t1bGwgV29vZHMgLSBCb3NzOjE=",
    ThievesAttic = "VGhpZXZlcycgVG93biAtIEF0dGljOjE=",
    ThievesBigKeyChest = "VGhpZXZlcycgVG93biAtIEJpZyBLZXkgQ2hlc3Q6MQ==",
    ThievesMapChest = "VGhpZXZlcycgVG93biAtIE1hcCBDaGVzdDox",
    ThievesCompassChest = "VGhpZXZlcycgVG93biAtIENvbXBhc3MgQ2hlc3Q6MQ==",
    ThievesAmbushChest = "VGhpZXZlcycgVG93biAtIEFtYnVzaCBDaGVzdDox",
    ThievesBigChest = "VGhpZXZlcycgVG93biAtIEJpZyBDaGVzdDox",
    ThievesBlindsCell = "VGhpZXZlcycgVG93biAtIEJsaW5kJ3MgQ2VsbDox",
    ThievesBoss = "VGhpZXZlcycgVG93biAtIEJvc3M6MQ==",
    IceBigKeyChest = "SWNlIFBhbGFjZSAtIEJpZyBLZXkgQ2hlc3Q6MQ==",
    IceCompassChest = "SWNlIFBhbGFjZSAtIENvbXBhc3MgQ2hlc3Q6MQ==",
    IceMapChest = "SWNlIFBhbGFjZSAtIE1hcCBDaGVzdDox",
    IceSpikeRoom = "SWNlIFBhbGFjZSAtIFNwaWtlIFJvb206MQ==",
    IceFreezorChest = "SWNlIFBhbGFjZSAtIEZyZWV6b3IgQ2hlc3Q6MQ==",
    IceTRoom = "SWNlIFBhbGFjZSAtIEljZWQgVCBSb29tOjE=",
    IceBigChest = "SWNlIFBhbGFjZSAtIEJpZyBDaGVzdDox",
    IceBoss = "SWNlIFBhbGFjZSAtIEJvc3M6MQ==",
    MireBigChest = "TWlzZXJ5IE1pcmUgLSBCaWcgQ2hlc3Q6MQ==",
    MireLobbyChest = "TWlzZXJ5IE1pcmUgLSBNYWluIExvYmJ5OjE=",
    MireBigKeyChest = "TWlzZXJ5IE1pcmUgLSBCaWcgS2V5IENoZXN0OjE=",
    MireCompassChest = "TWlzZXJ5IE1pcmUgLSBDb21wYXNzIENoZXN0OjE=",
    MireBridgeChest = "TWlzZXJ5IE1pcmUgLSBCcmlkZ2UgQ2hlc3Q6MQ==",
    MireMapChest = "TWlzZXJ5IE1pcmUgLSBNYXAgQ2hlc3Q6MQ==",
    MireSpikeChest = "TWlzZXJ5IE1pcmUgLSBTcGlrZSBDaGVzdDox",
    MireBoss = "TWlzZXJ5IE1pcmUgLSBCb3NzOjE=",
    TurtleChainChomps = "VHVydGxlIFJvY2sgLSBDaGFpbiBDaG9tcHM6MQ==",
    TurtleCompassChest = "VHVydGxlIFJvY2sgLSBDb21wYXNzIENoZXN0OjE=",
    TurtleRollerRoomLeft = "VHVydGxlIFJvY2sgLSBSb2xsZXIgUm9vbSAtIExlZnQ6MQ==",
    TurtleRollerRoomRight = "VHVydGxlIFJvY2sgLSBSb2xsZXIgUm9vbSAtIFJpZ2h0OjE=",
    TurtleBigChest = "VHVydGxlIFJvY2sgLSBCaWcgQ2hlc3Q6MQ==",
    TurtleBigKeyChest = "VHVydGxlIFJvY2sgLSBCaWcgS2V5IENoZXN0OjE=",
    TurtleCrystalrollerRoom = "VHVydGxlIFJvY2sgLSBDcnlzdGFyb2xsZXIgUm9vbTox",
    TurtleLaserBridgeLowerLeft = "VHVydGxlIFJvY2sgLSBFeWUgQnJpZGdlIC0gQm90dG9tIExlZnQ6MQ==",
    TurtleLaserBridgeLowerRight = "VHVydGxlIFJvY2sgLSBFeWUgQnJpZGdlIC0gQm90dG9tIFJpZ2h0OjE=",
    TurtleLaserBridgeTopLeft = "VHVydGxlIFJvY2sgLSBFeWUgQnJpZGdlIC0gVG9wIExlZnQ6MQ==",
    TurtleLaserBridgeTopRight = "VHVydGxlIFJvY2sgLSBFeWUgQnJpZGdlIC0gVG9wIFJpZ2h0OjE=",
    TurtleBoss = "VHVydGxlIFJvY2sgLSBCb3NzOjE=",
    GanonBobsTorch = "R2Fub24ncyBUb3dlciAtIEJvYidzIFRvcmNoOjE=",
    GanonStalfosRoomTopLeft = "R2Fub24ncyBUb3dlciAtIERNcyBSb29tIC0gVG9wIExlZnQ6MQ==",
    GanonStalfosRoomTopRight = "R2Fub24ncyBUb3dlciAtIERNcyBSb29tIC0gVG9wIFJpZ2h0OjE=",
    GanonStalfosRoomBottomLeft = "R2Fub24ncyBUb3dlciAtIERNcyBSb29tIC0gQm90dG9tIExlZnQ6MQ==",
    GanonStalfosRoomBottomRight = "R2Fub24ncyBUb3dlciAtIERNcyBSb29tIC0gQm90dG9tIFJpZ2h0OjE=",
    GanonRandoRoomTopLeft = "R2Fub24ncyBUb3dlciAtIFJhbmRvbWl6ZXIgUm9vbSAtIFRvcCBMZWZ0OjE=",
    GanonRandoRoomTopRight = "R2Fub24ncyBUb3dlciAtIFJhbmRvbWl6ZXIgUm9vbSAtIFRvcCBSaWdodDox",
    GanonRandoRoomBottomLeft = "R2Fub24ncyBUb3dlciAtIFJhbmRvbWl6ZXIgUm9vbSAtIEJvdHRvbSBMZWZ0OjE=",
    GanonRandoRoomBottomRight = "R2Fub24ncyBUb3dlciAtIFJhbmRvbWl6ZXIgUm9vbSAtIEJvdHRvbSBSaWdodDox",
    GanonFiresnakeRoom = "R2Fub24ncyBUb3dlciAtIEZpcmVzbmFrZSBSb29tOjE=",
    GanonMapChest = "R2Fub24ncyBUb3dlciAtIE1hcCBDaGVzdDox",
    GanonBigChest = "R2Fub24ncyBUb3dlciAtIEJpZyBDaGVzdDox",
    GanonHopeRoomLeft = "R2Fub24ncyBUb3dlciAtIEhvcGUgUm9vbSAtIExlZnQ6MQ==",
    GanonHopeRoomRight = "R2Fub24ncyBUb3dlciAtIEhvcGUgUm9vbSAtIFJpZ2h0OjE=",
    GanonBobsChest = "R2Fub24ncyBUb3dlciAtIEJvYidzIENoZXN0OjE=",
    GanonTileRoom = "R2Fub24ncyBUb3dlciAtIFRpbGUgUm9vbTox",
    GanonCompassRoomTopLeft = "R2Fub24ncyBUb3dlciAtIENvbXBhc3MgUm9vbSAtIFRvcCBMZWZ0OjE=",
    GanonCompassRoomTopRight = "R2Fub24ncyBUb3dlciAtIENvbXBhc3MgUm9vbSAtIFRvcCBSaWdodDox",
    GanonCompassRoomBottomLeft = "R2Fub24ncyBUb3dlciAtIENvbXBhc3MgUm9vbSAtIEJvdHRvbSBMZWZ0OjE=",
    GanonCompassRoomBottomRight = "R2Fub24ncyBUb3dlciAtIENvbXBhc3MgUm9vbSAtIEJvdHRvbSBSaWdodDox",
    GanonBigKeyChest = "R2Fub24ncyBUb3dlciAtIEJpZyBLZXkgQ2hlc3Q6MQ==",
    GanonBigKeyRoomLeft = "R2Fub24ncyBUb3dlciAtIEJpZyBLZXkgUm9vbSAtIExlZnQ6MQ==",
    GanonBigKeyRoomRight = "R2Fub24ncyBUb3dlciAtIEJpZyBLZXkgUm9vbSAtIFJpZ2h0OjE=",
    GanonHelmasaurRoomLeft = "R2Fub24ncyBUb3dlciAtIE1pbmkgSGVsbWFzYXVyIFJvb20gLSBMZWZ0OjE=",
    GanonHelmasaurRoomRight = "R2Fub24ncyBUb3dlciAtIE1pbmkgSGVsbWFzYXVyIFJvb20gLSBSaWdodDox",
    GanonPreMoldormChest = "R2Fub24ncyBUb3dlciAtIFByZS1Nb2xkb3JtIENoZXN0OjE=",
    GanonMoldormChest = "R2Fub24ncyBUb3dlciAtIE1vbGRvcm0gQ2hlc3Q6MQ==",
};

export enum PrizeLocations {
    EasternPalace = "RWFzdGVybiBQYWxhY2UgLSBQcml6ZTox",
    DesertPalace = "RGVzZXJ0IFBhbGFjZSAtIFByaXplOjE=",
    TowerOfHera = "VG93ZXIgb2YgSGVyYSAtIFByaXplOjE=",
    DarkPalace = "UGFsYWNlIG9mIERhcmtuZXNzIC0gUHJpemU6MQ==",
    SwampPalace = "U3dhbXAgUGFsYWNlIC0gUHJpemU6MQ==",
    SkullWoods = "U2t1bGwgV29vZHMgLSBQcml6ZTox",
    ThievesTown = "VGhpZXZlcycgVG93biAtIFByaXplOjE=",
    IcePalace = "SWNlIFBhbGFjZSAtIFByaXplOjE=",
    MiseryMire = "TWlzZXJ5IE1pcmUgLSBQcml6ZTox",
    TurtleRock = "VHVydGxlIFJvY2sgLSBQcml6ZTox",
};

export enum MedallionLocations {
    TurtleRock = "VHVydGxlIFJvY2sgTWVkYWxsaW9uOjE=",
    MiseryMire = "TWlzZXJ5IE1pcmUgTWVkYWxsaW9uOjE=",
};

export enum BottleLocations {
    WaterfallFairy = "V2F0ZXJmYWxsIEJvdHRsZTox",
    PyramidFairy = "UHlyYW1pZCBCb3R0bGU6MQ==",
};

export enum TextDialogs {
    UncleLeaving = "uncle_leaving_text",
    UncleDying = "uncle_dying_sewer",
    TutorialGuard1 = "tutorial_guard_1",
    TutorialGuard2 = "tutorial_guard_2",
    TutorialGuard3 = "tutorial_guard_3",
    TutorialGuard4 = "tutorial_guard_4",
    TutorialGuard5 = "tutorial_guard_5",
    TutorialGuard6 = "tutorial_guard_6",
    TutorialGuard7 = "tutorial_guard_7",
    PriestSancBeforeLeave = "priest_sanctuary_before_leave",
    SancEnter = "sanctuary_enter",
    ZeldaSancStory = "zelda_sanctuary_story",
    PriestBeforePendants = "priest_sanctuary_before_pendants",
    PriestAfterPendantsNoMasterSword = "priest_sanctuary_after_pendants_before_master_sword",
    PriestDying = "priest_sanctuary_dying",
    ZeldaSaveSewers = "zelda_save_sewers",
    PriestInfo = "priest_info",
    ZeldaSancBeforeLeave = "zelda_sanctuary_before_leave",
    TelepathicIntro = "telepathic_intro",
    TelepathicReminder = "telepathic_reminder",
    ZeldaGoToThrone = "zelda_go_to_throne",
    ZeldaPushThrone = "zelda_push_throne",
    ZeldaSwitchRoomPull = "zelda_switch_room_pull",
    ZeldaSaveLetsGo = "zelda_save_lets_go",
    ZeldaSaveRepeat = "zelda_save_repeat",
    ZeldaBeforePendants = "zelda_before_pendants",
    ZeldaAfterPendantsNoMasterSword = "zelda_after_pendants_before_master_sword",
    TelepathicZeldaAfterMasterSword = "telepathic_zelda_right_after_master_sword",
    ZeldaSewers = "zelda_sewers",
    ZeldaSwitchRoom = "zelda_switch_room",
    SahasrahlaWife = "kakariko_saharalasa_wife",
    SahasrahlaWifeSwordStory = "kakariko_saharalasa_wife_sword_story",
    SahasrahlaWifeClosing = "kakariko_saharalasa_wife_closing",
    SahasrahlaWifeAfterMasterSword = "kakariko_saharalasa_after_master_sword",
    KakarikoAlertGuards = "kakariko_alert_guards",
    SahasrahlaQuestHavePendants = "sahasrahla_quest_have_pendants",
    SahasrahlaQuestHaveMasterSword = "sahasrahla_quest_have_master_sword",
    SahasrahlaQuestInformation = "sahasrahla_quest_information",
    SahasrahlaBringCourage = "sahasrahla_bring_courage",
    SahasrahlaHaveIceRod = "sahasrahla_have_ice_rod",
    SahasrahlaBeatAga = "telepathic_sahasrahla_beat_agahnim",
    SahasrahlaBeatAgaNoPearl = "telepathic_sahasrahla_beat_agahnim_no_pearl",
    SahasrahlaHaveBootsNoIceRod = "sahasrahla_have_boots_no_icerod",
    SahasrahlaHaveCourage = "sahasrahla_have_courage",
    SahasrahlaFound = "sahasrahla_found",
    SignRainNorthOfLinksHouse = "sign_rain_north_of_links_house",
    SignNorthOfLinksHouse = "sign_north_of_links_house",
    SignDMAscent = "sign_path_to_death_mountain",
    SignLostWoods = "sign_lost_woods",
    SignZora = "sign_zoras",
    SignMagicShop = "sign_outside_magic_shop",
    SignDMDescent = "sign_death_mountain_cave_back",
    SignEastOfLinksHouse = "sign_east_of_links_house",
    SignSouthOfLumberjack = "sign_south_of_lumberjacks",
    SignEastOfDesert = "sign_east_of_desert",
    SignEastOfSanc = "sign_east_of_sanctuary",
    SignEastOfCastle = "sign_east_of_castle",
    SignNorthOfLake = "sign_north_of_lake",
    SignDesertThief = "sign_desert_thief",
    SignLumberjack = "sign_lumberjacks_house",
    SignNorthKakariko = "sign_north_kakariko",
    WitchBringMushroom = "witch_bring_mushroom",
    WitchBrewing = "witch_brewing_the_item",
    WitchAssistantNoBottle = "witch_assistant_no_bottle",
    WitchAssistantNoEmptyBottle = "witch_assistant_no_empty_bottle",
    WitchAssistantInfo = "witch_assistant_informational",
    WitchAssistantNoBottleBuying = "witch_assistant_no_bottle_buying",
    PotionShopBottlesFull = "potion_shop_no_empty_bottles",
    ItemGetLamp = "item_get_lamp",
    ItemGetBoomerang = "item_get_boomerang",
    ItemGetBow = "item_get_bow",
    ItemGetShovel = "item_get_shovel",
    ItemGetCape = "item_get_magic_cape",
    ItemGetPowder = "item_get_powder",
    ItemGetFlippers = "item_get_flippers",
    ItemGetGloves = "item_get_power_gloves",
    ItemGetCourage = "item_get_pendant_courage",
    ItemGetPower = "item_get_pendant_power",
    ItemGetWisdom = "item_get_pendant_wisdom",
    ItemGetMushroom = "item_get_mushroom",
    ItemGetBook = "item_get_book",
    ItemGetPearl = "item_get_moonpearl",
    ItemGetCompass = "item_get_compass",
    ItemGetMap = "item_get_map",
    ItemGetIceRod = "item_get_ice_rod",
    ItemGetFireRod = "item_get_fire_rod",
    ItemGetEther = "item_get_ether",
    ItemGetBombos = "item_get_bombos",
    ItemGetQuake = "item_get_quake",
    ItemGetHammer = "item_get_hammer",
    ItemGetFlute = "item_get_ocarina",
    ItemGetSomaria = "item_get_cane_of_somaria",
    ItemGetHookshot = "item_get_hookshot",
    ItemGetBombs = "item_get_bombs",
    ItemGetBottle = "item_get_bottle",
    ItemGetBigKey = "item_get_big_key",
    ItemGetMitts = "item_get_titans_mitts",
    ItemGetMirror = "item_get_magic_mirror",
    ItemGetFakeL2Sword = "item_get_fake_mastersword",
    PostItemGetL2Sword = "post_item_get_mastersword",
    ItemGetRedPotion = "item_get_red_potion",
    ItemGetGreenPotion = "item_get_green_potion",
    ItemGetBluePotion = "item_get_blue_potion",
    ItemGetNet = "item_get_bug_net",
    ItemGetBlueMail = "item_get_blue_mail",
    ItemGetRedMail = "item_get_red_mail",
    ItemGetL3Sword = "item_get_temperedsword",
    ItemGetL3Shield = "item_get_mirror_shield",
    ItemGetByrna = "item_get_cane_of_byrna",
    NoBigKey = "missing_big_key",
    NoMagic = "missing_magic",
    ItemGetBoots = "item_get_pegasus_boots",
    TalkingTreeInfoStart = "talking_tree_info_start",
    TalkingTreeInfo1 = "talking_tree_info_1",
    TalkingTreeInfo2 = "talking_tree_info_2",
    TalkingTreeInfo3 = "talking_tree_info_3",
    TalkingTreeInfo4 = "talking_tree_info_4",
    TalkingTreeOther = "talking_tree_other",
    ItemGetPowerAlt = "item_get_pendant_power_alt",
    ItemGetWisdomAlt = "item_get_pendant_wisdom_alt",
    ArrowGameChoice = "game_shooting_choice",
    ArrowGameYes = "game_shooting_yes",
    ArrowGameNo = "game_shooting_no",
    ArrowGameContinue = "game_shooting_continue",
    PondOfWishing = "pond_of_wishing",
    PondItemSelect = "pond_item_select",
    PondItemTest = "pond_item_test",
    PondWillUpgrade = "pond_will_upgrade",
    PondItemTestNo = "pond_item_test_no",
    PondItemTestNoNo = "pond_item_test_no_no",
    PondItemBoomerang = "pond_item_boomerang",
    PondItemShield = "pond_item_shield",
    PondItemSilvers = "pond_item_silvers",
    PondItemFillBottle = "pond_item_bottle_filled",
    PondItemSword = "pond_item_sword",
    CapacityFairyHappiness = "pond_of_wishing_happiness",
    CapacityFairyChoice = "pond_of_wishing_choice",
    CapacityFairyBombs = "pond_of_wishing_bombs",
    CapacityFairyArrows = "pond_of_wishing_arrows",
    CapacityFairyMaxUpgrades = "pond_of_wishing_full_upgrades",
    DMOldManMeet = "mountain_old_man_first",
    DMOldManDeadEnd = "mountain_old_man_deadend",
    DMOldManTurnRight = "mountain_old_man_turn_right",
    DMOldManLostAndAlone = "mountain_old_man_lost_and_alone",
    DMOldManDropOff = "mountain_old_man_drop_off",
    DMOldManInCavePreAga1 = "mountain_old_man_in_his_cave_pre_agahnim",
    DMOldManInCave = "mountain_old_man_in_his_cave",
    DMOldManInCavePostAga1 = "mountain_old_man_in_his_cave_post_agahnim",
    TavernOldManAwake = "tavern_old_man_awake",
    TavernOldManInactiveFlute = "tavern_old_man_unactivated_flute",
    TavernOldManKnowTreeInactiveFlute = "tavern_old_man_know_tree_unactivated_flute",
    TavernOldManHaveFlute = "tavern_old_man_have_flute",
    ChickenHutLady = "chicken_hut_lady",
    RunningMan = "running_man",
    SignRaceGame = "game_race_sign",
    SignBumperCave = "sign_bumper_cave",
    SignCatfish = "sign_catfish",
    SignNorthOfOutcasts = "sign_north_village_of_outcasts",
    SignSouthOfBumper = "sign_south_of_bumper_cave",
    SignEastOfPyramid = "sign_east_of_pyramid",
    SignEastOfBombShop = "sign_east_of_bomb_shop",
    SignEastOfMire = "sign_east_of_mire",
    SignInOutcasts = "sign_village_of_outcasts",
    SignWishingPond = "sign_before_wishing_pond",
    SignBeforeCatfishArea = "sign_before_catfish_area",
    CastleWallGuard = "castle_wall_guard",
    GateGuard = "gate_guard",
    HintTileEP = "telepathic_tile_eastern_palace",
    HintTileHera4F= "telepathic_tile_tower_of_hera_floor_4",
    HylianText1 = "hylian_text_1",
    PedTranslated = "mastersword_pedestal_translated",
    HintTileSpecRock = "telepathic_tile_spectacle_rock",
    HintTileSwamp = "telepathic_tile_swamp_entrance",
    HintTileThieves = "telepathic_tile_thieves_town_upstairs",
    HintTileMire = "telepathic_tile_misery_mire",
    HylianText2 = "hylian_text_2",
    DesertTranslated = "desert_entry_translated",
    HintTileGanon = "telepathic_tile_under_ganon",
    HintTilePOD = "telepathic_tile_palace_of_darkness",
    HintTileDesertTorch = "telepathic_tile_desert_bonk_torch_room",
    HintTileAgaTower = "telepathic_tile_castle_tower",
    HintTileIPLargeRoom = "telepathic_tile_ice_large_room",
    HintTileTurtleRock = "telepathic_tile_turtle_rock",
    HintTileIPEnter = "telepathic_tile_ice_entrace",
    HintTileIPStalfos = "telepathic_tile_ice_stalfos_knights_room",
    HintTileHeraEnter = "telepathic_tile_tower_of_hera_entrance",
    HoulihanRoom = "houlihan_room",
    CaughtBee = "caught_a_bee",
    CaughtFairy = "caught_a_fairy",
    NoEmptyBottles = "no_empty_bottles",
    RaceGameTime = "game_race_boy_time",
    RaceGameStart = "game_race_girl",
    RaceGameWin = "game_race_boy_success",
    RaceGameLose = "game_race_boy_failure",
    RaceGameAlreadyWon = "game_race_boy_already_won",
    RaceGameCheat = "game_race_boy_sneaky",
    BottleVendorChoice = "bottle_vendor_choice",
    BottleVendorGet = "bottle_vendor_get",
    BottleVendorNo = "bottle_vendor_no",
    BottleVendorHaveItem = "bottle_vendor_already_collected",
    BottleVendorBee = "bottle_vendor_bee",
    BottleVendorFish = "bottle_vendor_fish",
    HoboItemGetBottle = "hobo_item_get_bottle",
    SmithsWhatYouWant = "blacksmiths_what_you_want",
    SmithsPaywall = "blacksmiths_paywall",
    SmithsExtaOK = "blacksmiths_extra_okay",
    SmithsAlreadyTempered = "blacksmiths_tempered_already",
    SmithsTemperNo = "blacksmiths_temper_no",
    SmithsBogartSword = "blacksmiths_bogart_sword",
    SmithsGetSword = "blacksmiths_get_sword",
    SmithsFrogNotSaved = "blacksmiths_shop_before_saving",
    SmithsFrogSaved = "blacksmiths_shop_saving",
    SmithsGetFrog = "blacksmiths_collect_frog",
    SmithsStillWorking = "blacksmiths_still_working",
    SmithsSavingBows = "blacksmiths_saving_bows",
    SmithsHamerAnvil = "blacksmiths_hammer_anvil",
    StumpyStory = "dark_flute_boy_storytime",
    StumpyGetShovel = "dark_flute_boy_get_shovel",
    StumpyNoShovel = "dark_flute_boy_no_get_shovel",
    StumpyNoFlute = "dark_flute_boy_flute_not_found",
    StumpyAfterShovel = "dark_flute_boy_after_shovel_get",
    ShopFortuneTellerLWHint0 = "shop_fortune_teller_lw_hint_0",
    ShopFortuneTellerLWHint1 = "shop_fortune_teller_lw_hint_1",
    ShopFortuneTellerLWHint2 = "shop_fortune_teller_lw_hint_2",
    ShopFortuneTellerLWHint3 = "shop_fortune_teller_lw_hint_3",
    ShopFortuneTellerLWHint4 = "shop_fortune_teller_lw_hint_4",
    ShopFortuneTellerLWHint5 = "shop_fortune_teller_lw_hint_5",
    ShopFortuneTellerLWHint6 = "shop_fortune_teller_lw_hint_6",
    ShopFortuneTellerLWHint7 = "shop_fortune_teller_lw_hint_7",
    ShopFortuneTellerLWNoRupees = "shop_fortune_teller_lw_no_rupees",
    ShopFortuneTellerLW = "shop_fortune_teller_lw",
    ShopFortuneTellerLWPostHint = "shop_fortune_teller_lw_post_hint",
    ShopFortuneTellerLWHintNo = "shop_fortune_teller_lw_no",
    ShopFortuneTellerLWHint8 = "shop_fortune_teller_lw_hint_8",
    ShopFortuneTellerLWHint9 = "shop_fortune_teller_lw_hint_9",
    ShopFortuneTellerLWHint10 = "shop_fortune_teller_lw_hint_10",
    ShopFortuneTellerLWHint11 = "shop_fortune_teller_lw_hint_11",
    ShopFortuneTellerLWHint12 = "shop_fortune_teller_lw_hint_12",
    ShopFortuneTellerLWHint13 = "shop_fortune_teller_lw_hint_13",
    ShopFortuneTellerLWHint14 = "shop_fortune_teller_lw_hint_14",
    ShopFortuneTellerLWHint15 = "shop_fortune_teller_lw_hint_15",
    DarkSanctuary = "dark_sanctuary",
    DarkSanctuaryHint0 = "dark_sanctuary_hint_0",
    DarkSanctuaryNo = "dark_sanctuary_no",
    DarkSanctuaryHint1 = "dark_sanctuary_hint_1",
    DarkSanctuaryYes = "dark_sanctuary_yes",
    DarkSanctuaryHint2 = "dark_sanctuary_hint_2",
    SickKidNoBottle = "sick_kid_no_bottle",
    SickKidGetNet = "sick_kid_trade",
    SickKidPostNet = "sick_kid_post_trade",
    DesertThiefSitting = "desert_thief_sitting",
    DesertThiefFollow = "desert_thief_following",
    DesertThiefQuestion = "desert_thief_question",
    DesertThiefQuestionYes = "desert_thief_question_yes",
    DesertThiefPostItem = "desert_thief_after_item_get",
    DesertThiefReassure = "desert_thief_reassure",
    HylianText3 = "hylian_text_3",
    EtherTabletBook = "tablet_ether_book",
    BombosTabletBook = "tablet_bombos_book",
    MagicBatAwake = "magic_bat_wake",
    MagicBatHalfMagic = "magic_bat_give_half_magic",
    IntroMain = "intro_main",
    IntroThroneRoom = "intro_throne_room",
    IntroZeldaCell = "intro_zelda_cell",
    IntroAgahnim = "intro_agahnim",
    PurpleChest = "pickup_purple_chest",
    BombShop = "bomb_shop",
    BombShopBigBomb = "bomb_shop_big_bomb",
    BombShopBuyBigBomb = "bomb_shop_big_bomb_buy",
    ItemGetBigBomb = "item_get_big_bomb",
    KikiPay2 = "kiki_second_extortion",
    KikiPay2No = "kiki_second_extortion_no",
    KikiPay2Yes = "kiki_second_extortion_yes",
    KikiPay1 = "kiki_first_extortion",
    KikiPay1Yes = "kiki_first_extortion_yes",
    KikiPay1No = "kiki_first_extortion_no",
    KikiLeaveScreen = "kiki_leaving_screen",
    BlindInCell = "blind_in_the_cell",
    BlindInLight= "blind_by_the_light",
    BlindWrongWay = "blind_not_that_way",
    AginahL1SwordNoBook = "aginah_l1sword_no_book",
    AgainahL1SwordPendants = "aginah_l1sword_with_pendants",
    Aginah = "aginah",
    AginahNeedBetterSword = "aginah_need_better_sword",
    AginahHaveBetterSword = "aginah_have_better_sword",
    Catfish = "catfish",
    CatfishHaveItem = "catfish_after_item",
    LumberjackRight = "lumberjack_right",
    LumberjackLeft = "lumberjack_left",
    LumberjackLeftPostAga1 = "lumberjack_left_post_agahnim",
    FightingBrosRight = "fighting_brothers_right",
    FightingBrosRightOpen = "fighting_brothers_right_opened",
    FightingBrosLeft = "fighting_brothers_left",
    MaidenCrystal1 = "maiden_crystal_1",
    MaidenCrystal2 = "maiden_crystal_2",
    MaidenCrystal3 = "maiden_crystal_3",
    MaidenCrystal4 = "maiden_crystal_4",
    MaidenCrystal5 = "maiden_crystal_5",
    MaidenCrystal6 = "maiden_crystal_6",
    MaidenCrystal7 = "maiden_crystal_7",
    MaidenEnding = "maiden_ending",
    MaidenConfirmUnderstood = "maiden_confirm_undersood",
    BarrierBreaking = "barrier_breaking",
    MaidenCrystal7Again = "maiden_crystal_7_again",
    Aga1Confronted = "agahnim_zelda_teleport",
    Aga1RunAway = "agahnim_magic_running_away",
    Aga1FightStart = "agahnim_hide_and_seek_found",
    Aga1Defeated = "agahnim_defeated",
    Aga2FightStart = "agahnim_final_meeting",
    KingZora = "zora_meeting",
    KingZoraCost = "zora_tells_cost",
    KingZoraGetFlippers = "zora_get_flippers",
    KingZoraPoor = "zora_no_cash",
    KingZoraNo = "zora_no_buy_item",
    SahasrahlaGrandson = "kakariko_saharalasa_grandson",
    SahasrahlaGrandsonNext = "kakariko_saharalasa_grandson_next",
    DarkPalaceHintNPC = "dark_palace_tree_dude",
    FairyWishingPonds = "fairy_wishing_ponds",
    FairyWishingPondsNo = "fairy_wishing_ponds_no",
    PondOfWishingNo = "pond_of_wishing_no",
    PondOfWishingReturnItem = "pond_of_wishing_return_item",
    PondOfWishingThrow = "pond_of_wishing_throw",
    PondOfWishingPreSilvers = "pond_pre_item_silvers",
    CapacityFairyGreatLuck = "pond_of_wishing_great_luck",
    CapacityFairyGoodLuck = "pond_of_wishing_good_luck",
    CapacityFairyMehLuck = "pond_of_wishing_meh_luck",
    CapacityFairyBadLuck = "pond_of_wishing_bad_luck",
    PondOfWishingFortune= "pond_of_wishing_fortune",
    HeartPiece1 = "item_get_14_heart",
    HeartPiece2 = "item_get_24_heart",
    HeartPiece3 = "item_get_34_heart",
    HeartPiece4 = "item_get_whole_heart",
    SancHeart = "item_get_sanc_heart",
    FairyFountain = "fairy_fountain_refill",
    DarkDMBulliedNoPearl = "death_mountain_bullied_no_pearl",
    DarkDMBulliedWithPearl = "death_mountain_bullied_with_pearl",
    DarkDMBullyNoPearl = "death_mountain_bully_no_pearl",
    DarkDMBullyWithPearl = "death_mountain_bully_with_pearl",
    ShopDWEnter = "shop_darkworld_enter",
    ChestGameOutcasts = "game_chest_village_of_outcasts",
    ChestGamePoor = "game_chest_no_cash",
    ChestGameNotPlayed = "game_chest_not_played",
    ChestGamePlayed = "game_chest_played",
    ChestGameOutcastsPlay = "game_chest_village_of_outcasts_play",
    ShopFirstTime = "shop_first_time",
    ShopAlreadyHave = "shop_already_have",
    ShopBuyShield = "shop_buy_shield",
    ShopBuyRedPotion = "shop_buy_red_potion",
    ShopBuyArrows = "shop_buy_arrows",
    ShopBuyBombs = "shop_buy_bombs",
    ShopBuyBee = "shop_buy_bee",
    ShopBuyHeart = "shop_buy_heart",
    ShopFirstNoBottleBuy = "shop_first_no_bottle_buy",
    ShopBuyNoSpace = "shop_buy_no_space",
    GanonFallIn = "ganon_fall_in",
    GanonPhase3 = "ganon_phase_3",
    LostWoodsThief = "lost_woods_thief",
    BlindsHutGuy = "blinds_hut_dude",
    TriforceText = "end_triforce",
    ToppiFallen = "toppi_fallen",
    TavernFisherman = "kakariko_tavern_fisherman",
    ThiefMoney = "thief_money",
    DesertRupeeCave = "thief_desert_rupee_cave",
    IceRupeeCave = "thief_ice_rupee_cave",
    HintTileEDWCave = "telepathic_tile_south_east_darkworld_cave",
    Cukeman = "cukeman",
    Cukeman2 = "cukeman_2",
    PotionShopNoMoney = "potion_shop_no_cash",
    CuccoEasterEgg = "kakariko_powdered_chicken",
    KakarikoGambling = "game_chest_south_of_kakariko",
    ChestGameYes = "game_chest_play_yes",
    ChestGameNo = "game_chest_play_no",
    LostWoodsGambling = "game_chest_lost_woods",
    HotelMarioNoFlippers = "kakariko_flophouse_man_no_flippers",
    HotelMario = "kakariko_flophouse_man",
    MenuStart2 = "menu_start_2",
    MenuStart3 = "menu_start_3",
    MenuPause = "menu_pause",
    DigGameChoice = "game_digging_choice",
    DigGameStart = "game_digging_start",
    DigGamePoor = "game_digging_no_cash",
    DigGameTimeUp = "game_digging_end_time",
    DigGameComeBack = "game_digging_come_back_later",
    DigGameWithFollower = "game_digging_no_follower",
    MenuStart4 = "menu_start_4",
    GanonFallInAlt = "ganon_fall_in_alt",
    GanonPhase3Alt = "ganon_phase_3_alt",
    SignGlitchedWinners = "sign_east_death_mountain_bridge",
    FishMoney = "fish_money",
    SignGT = "sign_ganons_tower",
    SignGanon = "sign_ganon",
    GanonNoBow = "ganon_phase_3_no_bow",
    GanonNoSilversAlt = "ganon_phase_3_no_silvers_alt",
    GanonNoSilvers = "ganon_phase_3_no_silvers",
    GanonSilvers = "ganon_phase_3_silvers",
    Murahdahla = "murahdahla",
};